development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:1a97b15309b6b0f89bc646f786cebf03@pike.redistogo.com:11952/

  channel_prefix: message_me_production
